---
title: "US President Prediction"
subtitle: "Predict the results of 2024 US President Election"
author: 
  - Yun Chu
  - Felix Li
  - Wen Han Zhao 
thanks: "Code and data are available at: [https://github.com/younazhao/US-President-Prediction/tree/main](https://github.com/younazhao/US-President-Prediction/tree/main)."
date: 22 October 2024
date-format: long
abstract: "In this study, we aim to study the 2024 U.S. Presidential Election with the methodology of  polls of polls across various states. With the insightful analyses on polls provided by Redfiled & Wilton Strategies, the conducted survey on the population highlights various key point for the prediction of US president. Using Generalized Linear Models (GLMs), this report analyzes the accuracy of prediction in president votes through several key variables from pollster. The model incorporates variables such as pollscore, methodology, transparency_score and hypothetical. The prediction finding highlights the significance of candicate trustworthiness among the voter decision, providing insights for swing voters. This analysis offers valuable information into the potential electoral outcomes driving the 2024 US president election. "
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false
library(tidyverse)
library(knitr)
library(kableExtra)
library(readr)
library(dplyr)
```


# Introduction

Overview paragraph

Estimand paragraph

Results paragraph

Why it matters paragraph

Telegraphing paragraph: The remainder of this paper is structured as follows. @sec-data....






# Data {#sec-data}

## Overview

We use the statistical programming language R [@citeR].... Our data.... Following @tellingstories, we consider...

Overview text

## Measurement
	
Some paragraphs about how we go from a phenomena in the world to an entry in the dataset.

## Outcome variables

Talk way more about it. 

## Predictor variables

Add graphs, tables and text.

Use sub-sub-headings for each outcome variable and feel free to combine a few into one if they go together naturally.



# Model {#set-model}

As indicated in the @sec-data, we do not have a confident belief of priors of parameters of our model since Harris replace the role of Biden by indecent and we do not have enough data about her previous polling outcomes as a president candidate compared to Biden. Therefore, we would not use the bayesian model but instead using a more simple multilinear regression model which predicts the support rate of Trump and Harris using time towards elections date and pollsters as they are beliveved to highly corelated to the response variable in @sec-data. We would bulid 8 models whihc represent national trend and that of seven swing states. 
## Model set-up

Define $y_{i,\text{stateA}}$ as the percentage of support for a candicate in a poll in the specific state.

$$
y_{i,national} = \beta_{0,national} + \beta_{1,time,national} + \beta_{2,pollster,national} + \epsilon_{national}
$$ 
$$
y_{i,\text{AZ}} = \beta_{0,\text{AZ}} + \beta_{1,\text{time,AZ}} + \beta_{2,\text{pollster,AZ}} + \epsilon_{\text{AZ}}
$$
$$
y_{i,\text{FL}} = \beta_{0,\text{FL}} + \beta_{1,\text{time,FL}} + \beta_{2,\text{pollster,FL}} + \epsilon_{\text{FL}}
$$
$$
y_{i,\text{GA}} = \beta_{0,\text{GA}} + \beta_{1,\text{time,GA}} + \beta_{2,\text{pollster,GA}} + \epsilon_{\text{GA}}
$$
$$
y_{i,\text{MI}} = \beta_{0,\text{MI}} + \beta_{1,\text{time,MI}} + \beta_{2,\text{pollster,MI}} + \epsilon_{\text{MI}}
$$
$$
y_{i,\text{NC}} = \beta_{0,\text{NC}} + \beta_{1,\text{time,NC}} + \beta_{2,\text{pollster,NC}} + \epsilon_{\text{NC}}
$$
$$
y_{i,\text{PA}} = \beta_{0,\text{PA}} + \beta_{1,\text{time,PA}} + \beta_{2,\text{pollster,PA}} + \epsilon_{\text{PA}}
$$
$$
y_{i,\text{WI}} = \beta_{0,\text{WI}} + \beta_{1,\text{time,WI}} + \beta_{2,\text{pollster,WI}} + \epsilon_{\text{WI}}
$$

time:The date when the pollster starts polling

pollster: The pollster which run the polling

We run the model in R [@citeR].


### Model justification



# Results {#set-result}



\newpage

\appendix

# Appendix {-}


# Additional data details

## pollster methodology analysis

This survey was conducted by Redfield & Wilton Strategies to assess the voting intentions of eligible voters in key U.S. swing states ahead of the 2024 Presidential Election. The primary goal of this poll is to provide an accurate and timely snapshot of public opinion in states where electoral outcomes are uncertain and could have a decisive impact on the overall result of the election. Swing states, due to their political volatility and diverse voter bases, are critical in determining the balance of power in the U.S. electoral system. Understanding voter preferences in these states is essential for political analysts, campaigns, and the general public.

### Population of Interest
The population of interest for this survey consists of all eligible voters residing in major U.S. swing states, specifically Arizona, Florida, Georgia, Michigan, North Carolina, and Pennsylvania. These states are known for their fluctuating political alignments and are expected to play a crucial role in the upcoming election.

### Sampling Frame
The population sampled includes eligible voters from Arizona, Florida, Georgia, Michigan, North Carolina, and Pennsylvania. Participants were selected via an online panel.

### Sample
The sample sizes for each state were as follows:

Arizona: 750 respondents

Florida: 1,350 respondents

Georgia: 927 respondents

Michigan: 970 respondents

North Carolina: 880 respondents

Pennsylvania: 1,070 respondents

## Weakness & Strength of the methodology

In terms of strengths, Redfield & Wilton has a great reputation for producing reliable polling data. They have employ a mix of online and telephone survey, which add in various resources of collecting their data. This approach can help reduce bias. In addition, Redfield & Wilton often target swing states, which makes their polls results important to the US president election.

The weakness of their methodology would incorporate a certain potential bias based on their political leaning of their clients or media. This could cause a certain neutrality in their dataset. 

Overall, Redfield & Wilton has been considered as a competent, reputable and reliable pollster with his variaty and methodology on polls. Even though the pollster contained a potential bias, it has been a reliable resource in prediction of US president election. 


# Model details {#sec-model-details}



\newpage

# Appendix 2 - Idealized Methodology and Survey

## Overview

This section introduces an idealized methodology and survey with $100K budget to predict the 2024 US presidential election. The goal is to maximize the accuracy of the prediction under the budget. The subsections that describe the details of the idealized methodology and survey include sampling approach, respondents recruiting method, data validation, poll aggregation and the survey questions.

### Sampling Approach

Cluster sampling is the sampling approach used. Specifically clusters are the swing states as they are the states that would affect the election result, i.e. Arizona, Florida, Gegorgia, Iowa, Michigan, Nevada, North Carolina, Pennsylvania, and Wisconsin. In each swing state/clusters, units are selected based on postal code. Using simple random sampling, 100 distinct postal codes are randomly selected. People whose living address has the postal codes selected are the target respondents. For the postal codes that lie in the non-residential area, the postal codes would be ignored.

### Recruitment Strategy

The strategy to be implemented to recruit respondents is a combination of physical and online recruitment. 

If the building corresponds to the postal code is a condo building, a paper with QR code to the survey is going to be put in the lobby or elevator, or sent to residents through the property management. If the building is a residential house, then a letter with the QR code would be put in the mailbox. 

All respondents are rewarded with a $5 deposit to their bank account or a gift card of their choice. Each IP address is limited to answer the survey once.

### Data Validation

To improve accuracy of the prediction results, the following data validation approaches will be done.

* Postal Code Validation
    + All the postal codes got from respondents are going to be validated to check if it is one of the randomly selected postal codes. If not, the response would not be considered when the prediction is done.
* Just-for-Rewards Prevention
    + To identify the responses that are not seriously answered, the last question of the survey is set test if the respondents are serious and careful when answering the questions.
* Age Validity
    + Responses with age under 18 but answered "Yes" to "Are you registered to Vote" are discarded.


### Poll Aggregation

For each of the swing states, the result would be calculated based on the votes to Trump versus Harris because they are the candidates with the greatest chances of winning. Based on the decisiveness of the respondents and the likelihood of voting from the responses, the individual votes will be weighted when calculating the results for each swing states.

To aggregate the polls for all states, the result of each states is multiplied by its electoral votes. After summing the electoral votes for Trump or Harris, the estimated electoral votes that Trump or Harris get is available. The candidate that has more than 270 electoral votes would be predicted to win the election {@nationalarchives2024electoral}.

### Survey

Google form of the survey is available here:  https://docs.google.com/forms/d/1obaebX3zqw7WJEd1lHrF-DVBXdZt5tbjHofjsWj9zf8/prefill 

1. What is the postal code of where you live?

2. Are you registered to vote?

* Yes
* No

3. Who would you vote for?

* Donald Trump - Republican
* Kamala Harris - Democrat
* Other Candidates
* Not Decided Yet

4. How decisive are you to vote for the option you chose in the last question?

* Very Decisive
* Pretty Decisive
* A Bit Indecisive
* Very Indecisive

5. How likely are you to vote for the election?

* Very Likely
* A Bit Likely
* Not Likely

6. What age group are you in?

* 0 - 18
* 19 - 30
* 31 - 50
* 51 - 70
* 71+

7.

8.

9.

10. How many characters are present in the word "President"?

* 6
* 8
* 10
* None of the Above

### Budget Specification

* Physical and Online Recruitment: $30,000
* Rewards for Respondents: $50,000
* Data Collection & Validation: $10,000
* Other: $10,000

Total: $100,000

### Conclusion

The survey uses cluster sampling to sample the swing states based on postal codes. After data collection and validation, weighting based on the likelihood of voting and decisiveness of the respondents, the total votes for Donald Trump and Kamala Harris are calulated. The candidate with more than 270 votes are predicted to win the election{@nationalarchives2024electoral}.

# References




